services:
  server:
    container_name: sentiment_analyser
    build:
      context: .
      dockerfile: Dockerfile
    image: sentiment_analyser
    restart: unless-stopped
    init: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    ports:
      - "8000:8000"
    environment:
      - HF_HOME=/code/.cache
    env_file:
      - .env
    volumes:
      - hf_cache:/code/.cache
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    networks:
      - sentiment_net

volumes:
  hf_cache:
    name: sentiment-hf-cache

networks:
  sentiment_net:
    driver: bridge
